spring.application.name=potluck-portal
spring.data.mongodb.uri=mongodb://localhost:27017/yearup-potluck
spring.data.mongodb.database=yearup-potluck
okta.oauth2.issuer=https://yearup-potluck.us.auth0.com/
okta.oauth2.client-id=${AUTH0_CLIENT_ID}
okta.oauth2.client-secret=${AUTH0_CLIENT_SECRET}
